name: Manual test mcp agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Ask github agent about user
        uses: docker/cagent-action@v2.0.0
        with:
          agent: agentcatalog/github
          prompt: "Who is the user jeanlaurent on github?"
          mcp-gateway: true
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
